INSERT INTO DNA VALUES (1, 'DNA REGISTRADO 1', 'ATGCGA');
INSERT INTO DNA VALUES (2, 'DNA REGISTRADO 2', 'CAGTGC');
INSERT INTO DNA VALUES (3, 'DNA REGISTRADO 3', 'TTATGT');
INSERT INTO DNA VALUES (4, 'DNA REGISTRADO 4', 'AGAAGG');
INSERT INTO DNA VALUES (5, 'DNA REGISTRADO 5', 'CCCCTA');
INSERT INTO DNA VALUES (6, 'DNA REGISTRADO 6', 'TCACTG');